# Generated by Django 3.0.5 on 2020-05-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200507_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(default='چکیده مقاله موجود نیست', max_length=150),
        ),
    ]
