# Generated by Django 3.0.5 on 2020-05-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='promote',
            field=models.BooleanField(default=False, verbose_name='در اسلایدر نمایش داده شود'),
        ),
    ]
